import React from 'react'

function Text() {
    return (
        <div style={{ padding: "20px" }}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mauris enim, ullamcorper eu odio sit amet, pharetra finibus mi. Sed bibendum enim mauris. Curabitur accumsan a justo vulputate imperdiet. Vestibulum tempor erat et mattis condimentum. Proin porttitor nisi eu eleifend viverra. Etiam sapien diam, accumsan vitae nisi et, faucibus vulputate nisl. In fermentum convallis ex eget egestas. Vivamus mollis ex sed dolor lacinia blandit. Nulla vehicula quis neque sed consectetur. Mauris tincidunt sapien et est aliquet posuere. Nulla non luctus arcu. Donec aliquam, mi ut rutrum semper, justo turpis accumsan dolor, ac laoreet nisl libero id lacus.
            Aenean viverra laoreet faucibus. Sed accumsan, diam eget suscipit malesuada, est justo sagittis mauris, eget cursus purus ipsum quis velit. Donec quis nisi sit amet tellus elementum pretium. In vel consectetur ante. Cras id luctus purus. Suspendisse vitae quam lobortis, lobortis ante sit amet, posuere tellus. Cras gravida neque congue felis blandit sollicitudin. Pellentesque suscipit metus eros, eget ultrices elit cursus non. Vivamus malesuada nunc lectus, id faucibus dolor varius quis. Pellentesque ipsum ante, consequat sed nisi ut, dictum ultricies dui. Aenean consequat tortor eget ipsum venenatis, eget tincidunt tellus congue. Maecenas pharetra lacus eget purus facilisis, nec iaculis felis convallis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse volutpat ante ac tellus elementum lacinia. Sed neque neque, aliquet eu eros vel, ultrices euismod odio. Etiam ac lobortis dui.
            Morbi nec lectus id velit tristique dictum vulputate id erat. Donec feugiat non nibh eget pharetra. Integer eu imperdiet sapien. In vitae nisi sed turpis congue sollicitudin at at enim. Morbi facilisis quam vehicula felis tincidunt porttitor. Vestibulum cursus est ligula. Nunc commodo molestie purus in pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vulputate ullamcorper lacinia. Sed facilisis velit nisl, sit amet eleifend neque pulvinar et. Quisque et tortor tellus. Duis in mi sagittis, feugiat ante et, tincidunt diam. Morbi sollicitudin tellus non leo vestibulum, et pharetra magna facilisis.
            Aliquam lectus nisi, pellentesque et ligula id, vestibulum condimentum mi. Suspendisse fermentum imperdiet auctor. Aliquam odio eros, molestie id viverra sit amet, efficitur vel nulla. Nunc et interdum orci, in condimentum enim. Maecenas hendrerit aliquam sodales. Donec nec nisi sollicitudin ante tincidunt pharetra. Pellentesque dapibus sem sit amet leo condimentum, et egestas nisl efficitur. Fusce a molestie turpis. Pellentesque feugiat ultricies orci, ut luctus augue dignissim vitae.
            Proin eget gravida tortor. Pellentesque pharetra ullamcorper quam vel maximus. Morbi felis neque, ullamcorper quis tempus sed, sodales id urna. Praesent nunc odio, aliquam a erat sit amet, cursus sodales neque. Phasellus faucibus sed leo finibus consequat. Praesent id pellentesque ante. Proin eu lorem condimentum, tempus nisl maximus, gravida velit. Sed id magna in metus pharetra condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed sed semper massa. Pellentesque vitae ante enim. Integer et blandit augue, vel ullamcorper nunc. Nulla maximus eros a dignissim viverra. Vivamus imperdiet eget turpis et pulvinar.
            <br />
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mauris enim, ullamcorper eu odio sit amet, pharetra finibus mi. Sed bibendum enim mauris. Curabitur accumsan a justo vulputate imperdiet. Vestibulum tempor erat et mattis condimentum. Proin porttitor nisi eu eleifend viverra. Etiam sapien diam, accumsan vitae nisi et, faucibus vulputate nisl. In fermentum convallis ex eget egestas. Vivamus mollis ex sed dolor lacinia blandit. Nulla vehicula quis neque sed consectetur. Mauris tincidunt sapien et est aliquet posuere. Nulla non luctus arcu. Donec aliquam, mi ut rutrum semper, justo turpis accumsan dolor, ac laoreet nisl libero id lacus.
            Aenean viverra laoreet faucibus. Sed accumsan, diam eget suscipit malesuada, est justo sagittis mauris, eget cursus purus ipsum quis velit. Donec quis nisi sit amet tellus elementum pretium. In vel consectetur ante. Cras id luctus purus. Suspendisse vitae quam lobortis, lobortis ante sit amet, posuere tellus. Cras gravida neque congue felis blandit sollicitudin. Pellentesque suscipit metus eros, eget ultrices elit cursus non. Vivamus malesuada nunc lectus, id faucibus dolor varius quis. Pellentesque ipsum ante, consequat sed nisi ut, dictum ultricies dui. Aenean consequat tortor eget ipsum venenatis, eget tincidunt tellus congue. Maecenas pharetra lacus eget purus facilisis, nec iaculis felis convallis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse volutpat ante ac tellus elementum lacinia. Sed neque neque, aliquet eu eros vel, ultrices euismod odio. Etiam ac lobortis dui.
            Morbi nec lectus id velit tristique dictum vulputate id erat. Donec feugiat non nibh eget pharetra. Integer eu imperdiet sapien. In vitae nisi sed turpis congue sollicitudin at at enim. Morbi facilisis quam vehicula felis tincidunt porttitor. Vestibulum cursus est ligula. Nunc commodo molestie purus in pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vulputate ullamcorper lacinia. Sed facilisis velit nisl, sit amet eleifend neque pulvinar et. Quisque et tortor tellus. Duis in mi sagittis, feugiat ante et, tincidunt diam. Morbi sollicitudin tellus non leo vestibulum, et pharetra magna facilisis.
            Aliquam lectus nisi, pellentesque et ligula id, vestibulum condimentum mi. Suspendisse fermentum imperdiet auctor. Aliquam odio eros, molestie id viverra sit amet, efficitur vel nulla. Nunc et interdum orci, in condimentum enim. Maecenas hendrerit aliquam sodales. Donec nec nisi sollicitudin ante tincidunt pharetra. Pellentesque dapibus sem sit amet leo condimentum, et egestas nisl efficitur. Fusce a molestie turpis. Pellentesque feugiat ultricies orci, ut luctus augue dignissim vitae.
            Proin eget gravida tortor. Pellentesque pharetra ullamcorper quam vel maximus. Morbi felis neque, ullamcorper quis tempus sed, sodales id urna. Praesent nunc odio, aliquam a erat sit amet, cursus sodales neque. Phasellus faucibus sed leo finibus consequat. Praesent id pellentesque ante. Proin eu lorem condimentum, tempus nisl maximus, gravida velit. Sed id magna in metus pharetra condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed sed semper massa. Pellentesque vitae ante enim. Integer et blandit augue, vel ullamcorper nunc. Nulla maximus eros a dignissim viverra. Vivamus imperdiet eget turpis et pulvinar.
            <br />
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mauris enim, ullamcorper eu odio sit amet, pharetra finibus mi. Sed bibendum enim mauris. Curabitur accumsan a justo vulputate imperdiet. Vestibulum tempor erat et mattis condimentum. Proin porttitor nisi eu eleifend viverra. Etiam sapien diam, accumsan vitae nisi et, faucibus vulputate nisl. In fermentum convallis ex eget egestas. Vivamus mollis ex sed dolor lacinia blandit. Nulla vehicula quis neque sed consectetur. Mauris tincidunt sapien et est aliquet posuere. Nulla non luctus arcu. Donec aliquam, mi ut rutrum semper, justo turpis accumsan dolor, ac laoreet nisl libero id lacus.
            Aenean viverra laoreet faucibus. Sed accumsan, diam eget suscipit malesuada, est justo sagittis mauris, eget cursus purus ipsum quis velit. Donec quis nisi sit amet tellus elementum pretium. In vel consectetur ante. Cras id luctus purus. Suspendisse vitae quam lobortis, lobortis ante sit amet, posuere tellus. Cras gravida neque congue felis blandit sollicitudin. Pellentesque suscipit metus eros, eget ultrices elit cursus non. Vivamus malesuada nunc lectus, id faucibus dolor varius quis. Pellentesque ipsum ante, consequat sed nisi ut, dictum ultricies dui. Aenean consequat tortor eget ipsum venenatis, eget tincidunt tellus congue. Maecenas pharetra lacus eget purus facilisis, nec iaculis felis convallis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse volutpat ante ac tellus elementum lacinia. Sed neque neque, aliquet eu eros vel, ultrices euismod odio. Etiam ac lobortis dui.
            Morbi nec lectus id velit tristique dictum vulputate id erat. Donec feugiat non nibh eget pharetra. Integer eu imperdiet sapien. In vitae nisi sed turpis congue sollicitudin at at enim. Morbi facilisis quam vehicula felis tincidunt porttitor. Vestibulum cursus est ligula. Nunc commodo molestie purus in pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vulputate ullamcorper lacinia. Sed facilisis velit nisl, sit amet eleifend neque pulvinar et. Quisque et tortor tellus. Duis in mi sagittis, feugiat ante et, tincidunt diam. Morbi sollicitudin tellus non leo vestibulum, et pharetra magna facilisis.
            Aliquam lectus nisi, pellentesque et ligula id, vestibulum condimentum mi. Suspendisse fermentum imperdiet auctor. Aliquam odio eros, molestie id viverra sit amet, efficitur vel nulla. Nunc et interdum orci, in condimentum enim. Maecenas hendrerit aliquam sodales. Donec nec nisi sollicitudin ante tincidunt pharetra. Pellentesque dapibus sem sit amet leo condimentum, et egestas nisl efficitur. Fusce a molestie turpis. Pellentesque feugiat ultricies orci, ut luctus augue dignissim vitae.
            Proin eget gravida tortor. Pellentesque pharetra ullamcorper quam vel maximus. Morbi felis neque, ullamcorper quis tempus sed, sodales id urna. Praesent nunc odio, aliquam a erat sit amet, cursus sodales neque. Phasellus faucibus sed leo finibus consequat. Praesent id pellentesque ante. Proin eu lorem condimentum, tempus nisl maximus, gravida velit. Sed id magna in metus pharetra condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed sed semper massa. Pellentesque vitae ante enim. Integer et blandit augue, vel ullamcorper nunc. Nulla maximus eros a dignissim viverra. Vivamus imperdiet eget turpis et pulvinar.
        </div>
    )
}

export default Text